//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOBSEEKER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class application
    {
        public int ID { get; set; }
        public string username { get; set; }
        public string userimg { get; set; }
        public string useremail { get; set; }
        public string userid { get; set; }
        public string comemail { get; set; }
        public string application_tittle { get; set; }
        public string application_locat { get; set; }
    }
}
