//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOBSEEKER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public string website { get; set; }
        public string Cover { get; set; }
        public string logo { get; set; }
        public string discription { get; set; }
        public string industry { get; set; }
        public Nullable<int> founded { get; set; }
        public string size { get; set; }
        public string country { get; set; }
        public string state { get; set; }
        public string address { get; set; }
        public string facebook { get; set; }
        public string twitter { get; set; }
        public string linkdin { get; set; }
        public string instagram { get; set; }
        public string img1 { get; set; }
        public string img2 { get; set; }
        public string img3 { get; set; }
        public string img4 { get; set; }
    }
}
