//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOBSEEKER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        public int ID { get; set; }
        public string title { get; set; }
        public string locat { get; set; }
        public string category { get; set; }
        public string overview { get; set; }
        public string responsiblities { get; set; }
        public string skills { get; set; }
        public string experince { get; set; }
        public string lvl { get; set; }
        public string typE { get; set; }
        public string salary { get; set; }
        public string company { get; set; }
        public string cover { get; set; }
    }
}
