//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOBSEEKER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobprofile
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string title { get; set; }
        public string location { get; set; }
        public string phone { get; set; }
        public string cover { get; set; }
        public string img { get; set; }
        public string about { get; set; }
        public string skills1 { get; set; }
        public string skills2 { get; set; }
        public string skills3 { get; set; }
        public string skills4 { get; set; }
        public string experincetitle1 { get; set; }
        public string company1 { get; set; }
        public string time1 { get; set; }
        public string discription1 { get; set; }
        public string experincetitle2 { get; set; }
        public string company2 { get; set; }
        public string time2 { get; set; }
        public string discription2 { get; set; }
        public string etitle1 { get; set; }
        public string eschool1 { get; set; }
        public string etime1 { get; set; }
        public string edisc1 { get; set; }
        public string etitle2 { get; set; }
        public string eschool2 { get; set; }
        public string etime2 { get; set; }
        public string edisc2 { get; set; }
    }
}
